### ISSUE TITLE
MY module not show in Lsposed repo

### ISSUE THREAD

**Issue by Android1500** [Xposed-Modules-Repo/org.meowcat.example#1]
I submited already my module but it not show in lsposed repo

**Comment by yujincheng08** [comment]
wait patiently. The schedule update is not yet triggered.

**Comment by Android1500** [comment]
> wait patiently. The schedule update is not yet triggered.

Thanks for update me asap so any idea  when schedule update will triggered?

**Comment by JasonKhew96** [comment]
> I submited already my module but it not show in lsposed repo

![image](https://user-images.githubusercontent.com/29531167/120878831-91de7e80-c5f1-11eb-8e7a-e657612ec19a.png)

Skipped due to no **Support/Discussion URL**
https://github.com/Xposed-Modules-Repo/org.meowcat.example#supportdiscussion-url-

**Comment by Android1500** [comment]
> > I submited already my module but it not show in lsposed repo
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/29531167/120878831-91de7e80-c5f1-11eb-8e7a-e657612ec19a.png)
> 
> 
> 
> Skipped due to no **Support/Discussion URL**
> 
> https://github.com/Xposed-Modules-Repo/org.meowcat.example#supportdiscussion-url-

Thanks i got it
